version: '3.8'

services:
  node_backend:
    container_name: nodepgcrud
    image: nodepgcrud:0.0.4
    build: 
      context: .
    ports:
      - "3002:3002"
    environment:
      - EXTERNAL_PORT=3002
      - PGDATABASE=nodepgcrud
      - PGUSER=ajay
      - PGPASSWORD=12345
      - PGHOST=node_db
    depends_on:
      - node_db
  node_db:
      container_name: node_db
      image: "postgres:12"
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=ajay
        - POSTGRES_PASSWORD=12345
        - POSTGRES_DB=nodepgcrud
      volumes:
        - nps_data:/var/lib/postresql/data

volumes:
  nps_data: {}
